export const ACTION = {
  GET_USER: "GET_USERS",
  SHOW_USER: "SHOW_USER",
  LOADING: "LOADING",
  CLEAR: "CLEAR",
  SET_ALERT: "SET_ALERT",
  REMOVE_ALERT: "REMOVE_ALERT",
  GET_REPO: "GET_REPO",
};
